/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.5.1/userguide/building_java_projects.html
 */

group = "org.eclipse"
version = "v1.0.0-alpha"

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    // application
    java
    war
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()

    mavenLocal()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.2")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.0.1-jre")

    providedCompile("jakarta.platform:jakarta.jakartaee-api:10.0.0")
    // implementation("jakarta.platform:jakarta.jakartaee-web-api:9.0.0")

    // implementation("org.glassfish.jersey.containers:jersey-container-servlet:3.1.0")
    
    


    // implementation("org.glassfish.jersey.containers:jersey-container-servlet:3.1.0")
    // implementation("org.glassfish.jersey.inject:jersey-hk2:3.1.0")
    // implementation("org.glassfish.jersey.media:jersey-media-json-binding:3.1.0")
    // implementation("org.glassfish.jersey.ext.cdi:jersey-cdi1x:3.1.0")
    // implementation("org.glassfish.jersey.ext.cdi:jersey-cdi1x-servlet:3.1.0")
    // implementation("org.glassfish.jersey.ext.cdi:jersey-cdi1x-ban-custom-hk2-binding:3.1.0")
}



// application {
//     // Define the main class for the application.
//     mainClass.set("org.eclipse.trace.coordinator.App")
// }

tasks.war {
    archiveBaseName.set("trace-coordinator")
}


tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
