@expUuid = cde21a0a-35cd-37d4-8fdc-d1ecad068f6b
@apiUrl = {{baseUrl}}/experiments/{{expUuid}}/graph

@workerId =25

### Get worker

GET {{apiUrl}}/workers/{{workerId}} 

### Get Vertex indexes

GET {{apiUrl}}/indexes
    ?direction= 

### Get unmatched Vertex Worker 22 timestamp 1539975458516555207
# [4017021289, 0, 2] - [4017021289, 0, 2]
# [3448148819, 4017021290, 18]
GET {{apiUrl}}/vertexes
    ?start=
    &end=
    &direction=

### Create a critical-path
POST {{apiUrl}}/critical-path
Content-Type: application/json

{
  "parameters": {
    "startVertex": {
      "workerId": 25,
      "timestamp": 1539975458513675734
    },
    "endVertex": {
      "workerId": 16,
      "timestamp": 1539975458519193565
    }
  }
}


