@expUuid = cde21a0a-35cd-37d4-8fdc-d1ecad068f6b
@apiUrl = {{baseUrl}}/experiments/{{expUuid}}/graph

@workerId =

### Get worker

GET {{apiUrl}}/workers/{{workerId}} 

### Get Vertex indexes

GET {{apiUrl}}/indexes
    ?direction= 

### Get unmatched Vertex

GET {{apiUrl}}/vertexes
    ?start=1539975458513731973
    &end=1539975458519193564
    &direction=EFFECT

### Create a critical-path
POST {{apiUrl}}/critical-path
Content-Type: application/json

{
  "parameters": {
    "startVertex": {
      "workerId": 133,
      "timestamp": 1539975461621254810
    },
    "endVertex": {
      "workerId": 37,
      "timestamp": 1539975461621271632
    }
  }
}
