version: "3.9"

services:
  trace-coordinator:
    container_name: Trace-Coordinator
    image: trace-coordinator
    ports:
      - "8080:8080"

  trace-server:
    image: trace-server
    deploy:
      mode: replicated
      replicas: 4
    volumes:
      - $HOME/ws/samples-traces:$HOME/traces:ro
    ports:
      - "8081-8090:8080"
