version: "3.9"

services:
  trace-coordinator:
    container_name: Trace-Coordinator
    image: trace-coordinator
    ports:
      - "8080:8080"

  trace-server-1:
    container_name: Trace-Server-1
    image: trace-server
    volumes:
      - ${PWD}/traces/103-compare-package-managers/apt:/apt:ro
    ports:
      - "8081:8080"

  trace-server-2:
    container_name: Trace-Server-2
    image: trace-server
    volumes:
      - ${PWD}/traces/103-compare-package-managers/pacman:/pacman:ro
    ports:
      - "8082:8080"

  trace-server-3:
    container_name: Trace-Server-3
    image: trace-server
    volumes:
      - ${PWD}/traces/103-compare-package-managers/yum:/yum:ro
    ports:
      - "8083:8080"

  trace-server-4:
    container_name: Trace-Server-4
    image: trace-server
    volumes:
      - ${PWD}/traces/103-compare-package-managers/zypper:/zypper:ro
    ports:
      - "8084:8080"
