FROM gradle:8.1.1-jdk17-alpine AS packager

ARG USERNAME
ARG GITHUB_TOKEN

ENV USERNAME=${USERNAME}
ENV GITHUB_TOKEN=${GITHUB_TOKEN}


COPY ./ /app/

WORKDIR /app/

RUN ./gradlew build -x test && ./gradlew installDist
ENV HOST="0.0.0.0"
ENV PORT="8080"
FROM eclipse-temurin:17-alpine

COPY --from=packager /app/app/build/install/trace-coordinator/ /app/
WORKDIR /app/bin

CMD ["./trace-coordinator"]
