FROM quay.io/wildfly/wildfly:27.0.0.Final-jdk11

COPY app/build/libs/trace-coordinator-*.war /opt/jboss/wildfly/standalone/deployments/trace-coordinator.war

## Uncomment if you want to configure the coordinator
# COPY .trace-coordinator.yml /opt/jboss


## Uncomment if you want to add system property
# CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0"]