---
- hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Install Podman
      apt:
        name: podman
        update_cache: yes
    - name: Set Podman registries conf
      shell: "{{ item }} >> /etc/containers/registries.conf"
      with_items:
      - 'echo "[registries.search]"' 
      - 'echo "registries=[\"docker.io\"]"'

- hosts: master
  become: true
  gather_facts: true
  tasks:


- hosts: workers
  become: true
  gather_facts: true
  tasks:

